version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
    # volumes:
    #   - ./data:/tmp/localstack